version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /services/api
    schedule:
      interval: weekly
    groups:
      api-python:
        patterns: ["*"]
  - package-ecosystem: pip
    directory: /services/morpheus-sandbox
    schedule:
      interval: weekly
    groups:
      sandbox-python:
        patterns: ["*"]
