import { useState, useEffect } from "react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { 
  BarChart3, 
  TrendingUp, 
  Users, 
  DollarSign, 
  Download, 
  Share, 
  Sparkles,
  Activity,
  Target
} from "lucide-react";

const DashboardPreview = () => {
  const [animationStep, setAnimationStep] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setAnimationStep((prev) => (prev + 1) % 4);
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  const sampleData = [
    { month: "Jan", revenue: 12000, users: 150 },
    { month: "Feb", revenue: 19000, users: 280 },
    { month: "Mar", revenue: 25000, users: 420 },
    { month: "Apr", revenue: 31000, users: 580 },
    { month: "May", revenue: 38000, users: 720 },
    { month: "Jun", revenue: 45000, users: 890 }
  ];

  const metrics = [
    { 
      label: "Monthly Revenue", 
      value: "$45,000", 
      change: "+18.2%", 
      icon: DollarSign,
      trend: "up"
    },
    { 
      label: "Active Users", 
      value: "890", 
      change: "+12.5%", 
      icon: Users,
      trend: "up"
    },
    { 
      label: "Conversion Rate", 
      value: "3.8%", 
      change: "+0.5%", 
      icon: Target,
      trend: "up"
    },
    { 
      label: "Growth Rate", 
      value: "24%", 
      change: "+2.1%", 
      icon: TrendingUp,
      trend: "up"
    }
  ];

  return (
    <div className="flex-1 p-6 overflow-y-auto bg-gradient-to-br from-background to-background/50">
      {/* Header Actions */}
      <div className="flex justify-between items-center mb-6">
        <div>
          <h3 className="text-lg font-semibold mb-1">Revenue Dashboard</h3>
          <p className="text-sm text-muted-foreground">Generated by AI • Real-time preview</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="border-border/50">
            <Share className="w-4 h-4 mr-1" />
            Share
          </Button>
          <Button variant="outline" size="sm" className="border-border/50">
            <Download className="w-4 h-4 mr-1" />
            Export
          </Button>
        </div>
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        {metrics.map((metric, index) => (
          <Card 
            key={metric.label} 
            className={`glass-panel p-4 hover:scale-105 transition-all duration-300 ${
              animationStep === index ? 'glow-primary' : ''
            }`}
            style={{ animationDelay: `${index * 0.1}s` }}
          >
            <div className="flex items-start justify-between">
              <div>
                <p className="text-sm text-muted-foreground mb-1">{metric.label}</p>
                <p className="text-2xl font-bold mb-1">{metric.value}</p>
                <div className="flex items-center gap-1">
                  <TrendingUp className="w-3 h-3 text-success" />
                  <span className="text-xs text-success">{metric.change}</span>
                </div>
              </div>
              <div className="w-8 h-8 rounded-lg bg-primary/20 flex items-center justify-center">
                <metric.icon className="w-4 h-4 text-primary" />
              </div>
            </div>
          </Card>
        ))}
      </div>

      {/* Main Chart */}
      <Card className="glass-panel p-6 mb-6">
        <div className="flex items-center justify-between mb-4">
          <h4 className="text-lg font-semibold">Revenue Trend</h4>
          <Badge variant="secondary" className="bg-accent/20 text-accent border-accent/30">
            <Activity className="w-3 h-3 mr-1" />
            Live Data
          </Badge>
        </div>
        
        {/* Animated Chart Bars */}
        <div className="h-64 flex items-end justify-between gap-3">
          {sampleData.map((data, index) => (
            <div key={data.month} className="flex flex-col items-center flex-1">
              <div className="relative w-full bg-border/30 rounded-t-lg overflow-hidden">
                <div 
                  className="bg-gradient-to-t from-primary to-accent rounded-t-lg transition-all duration-1000 ease-out"
                  style={{ 
                    height: `${(data.revenue / 45000) * 200}px`,
                    animationDelay: `${index * 0.2}s`
                  }}
                />
                {animationStep === 2 && (
                  <div className="absolute top-2 left-1/2 -translate-x-1/2 text-xs text-white font-medium">
                    ${(data.revenue / 1000).toFixed(0)}k
                  </div>
                )}
              </div>
              <span className="text-xs text-muted-foreground mt-2">{data.month}</span>
            </div>
          ))}
        </div>
      </Card>

      {/* AI Insights Panel */}
      <Card className="glass-panel p-6">
        <div className="flex items-center gap-2 mb-4">
          <Sparkles className="w-5 h-5 text-accent" />
          <h4 className="text-lg font-semibold">AI Insights</h4>
        </div>
        
        <div className="space-y-3">
          <div className="flex items-start gap-3 p-3 rounded-lg bg-primary/10 border border-primary/20">
            <div className="w-2 h-2 bg-primary rounded-full mt-2 animate-pulse"></div>
            <div>
              <p className="text-sm font-medium text-primary mb-1">Revenue Growth Acceleration</p>
              <p className="text-sm text-muted-foreground">
                Your MRR has grown 23% faster in Q2 compared to Q1, with the strongest gains in May and June.
              </p>
            </div>
          </div>
          
          <div className="flex items-start gap-3 p-3 rounded-lg bg-accent/10 border border-accent/20">
            <div className="w-2 h-2 bg-accent rounded-full mt-2 animate-pulse"></div>
            <div>
              <p className="text-sm font-medium text-accent mb-1">User Acquisition Trend</p>
              <p className="text-sm text-muted-foreground">
                Customer acquisition is outpacing revenue growth, indicating healthy unit economics.
              </p>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
};

export default DashboardPreview;