export const connectorModalStyles = {
  content: "sm:max-w-[425px] bg-background text-foreground border-border outline-none z-[200]",
  loading: "flex flex-col items-center justify-center py-8 text-muted-foreground",
  loadingCompact: "flex flex-col items-center py-6 text-muted-foreground",
  mutedText: "text-muted-foreground",
  subtleText: "text-xs text-muted-foreground",
  label: "text-sm font-medium text-foreground",
  tabsList: "grid w-full grid-cols-2 bg-muted border border-border p-1 rounded-lg",
  tabsListWithMargin: "grid w-full grid-cols-2 bg-muted border border-border p-1 rounded-lg mb-4",
  tabsTrigger: "data-[state=active]:bg-background data-[state=active]:text-foreground rounded-md text-sm transition-all",
  selectTrigger: "w-full bg-background border-border text-foreground",
  selectContent: "bg-popover border-border text-popover-foreground z-[201]",
  selectLabel: "text-xs text-muted-foreground uppercase tracking-wide px-2 py-1",
  selectMetaText: "text-[10px] text-muted-foreground uppercase tracking-wider",
  dateInput: "date-input-themed w-full px-3 py-2 pr-10 rounded-md border border-border bg-background text-sm text-foreground",
  dateIcon: "pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground",
  emptyState: "text-center py-6 text-muted-foreground text-sm border border-border rounded-lg bg-muted/30",
  emptyStateCompact: "text-center py-5 text-muted-foreground text-sm border border-border rounded-lg bg-muted/30",
  connectedText: "text-sm font-medium truncate text-foreground",
  ghostButton: "text-muted-foreground hover:text-foreground hover:bg-muted",
  ghostButtonSmall: "h-8 text-muted-foreground hover:text-foreground hover:bg-muted px-2",
  outlineButton: "bg-background border-border text-foreground hover:bg-muted",
  infoPanel: "p-4 bg-muted/30 border border-border rounded-lg text-sm text-muted-foreground space-y-2",
  disconnectedCard: "flex items-center justify-between p-3 border border-border rounded-lg bg-background hover:bg-muted transition-colors cursor-pointer group",
  disconnectedIcon: "w-8 h-8 rounded-md bg-muted/60 flex items-center justify-center shrink-0 group-hover:bg-muted transition-colors",
  disconnectedText: "text-sm text-foreground",
  searchBox: "flex items-center space-x-2 bg-background border border-border rounded-md p-2",
  searchInput: "bg-transparent border-none text-sm text-foreground placeholder:text-muted-foreground outline-none w-full",
  selectionPanel: "max-h-60 overflow-y-auto space-y-2 pr-1 border border-border rounded-md p-2 bg-muted/30",
  selectionRow: "flex items-start space-x-3 p-2 hover:bg-muted rounded-md cursor-pointer transition-colors",
  selectionRowWithDivider: "flex items-start space-x-3 p-2 hover:bg-muted rounded-md cursor-pointer transition-colors border-b border-border mb-1",
  checkbox: "mt-0.5 border-border data-[state=checked]:bg-blue-600 data-[state=checked]:border-blue-600",
  selectionTitle: "text-sm font-medium text-foreground truncate leading-tight",
  selectionMeta: "text-[11px] text-muted-foreground mt-1",
  noDataTitle: "text-xl font-semibold text-foreground mb-2",
  noDataDescription: "text-center text-sm text-muted-foreground mb-8 max-w-[300px]",
  secondaryActionButton: "w-full bg-background border-border text-foreground hover:bg-muted transition-all font-medium",
};
