import React from 'react';
import DocsLayout from '@/components/layout/DocsLayout';

const Terms = () => {
  const metadata = {
    title: "Terms of Service",
    effectiveDate: "March 12, 2026",
    description: "Welcome to Dreamify (\"we,\" \"our,\" or \"us\"). By accessing or using our website (app.dreamify.dev) and our AI-powered data analytics platform (collectively, the \"Service\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, please do not use our Service."
  };

  const toc = [
    { id: "description-of-service", title: "1. Description of Service" },
    { id: "informational-purposes", title: "2. Informational Purposes Only" },
    { id: "user-accounts-security", title: "3. User Accounts and Security" },
    { id: "user-data-content", title: "4. User Data and Content" },
    { id: "acceptable-use", title: "5. Acceptable Use Policy" },
    { id: "third-party-services", title: "6. Third-Party Services and APIs" },
    { id: "disclaimer-warranties", title: "7. Disclaimer of Warranties" },
    { id: "limitation-liability", title: "8. Limitation of Liability" },
    { id: "modifications-terms", title: "9. Modifications to the Terms" },
    { id: "contact-us", title: "10. Contact Us" },
  ];

  return (
    <DocsLayout metadata={metadata} toc={toc}>
      <section id="description-of-service">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">1. Description of Service</h2>
        <p className="text-muted-foreground leading-relaxed">
          Dreamify provides an artificial intelligence-driven data visualization and analytics platform. The Service allows users to connect third-party data sources (e.g., Google Analytics, Google Sheets) or upload static files (e.g., CSVs) to generate dynamic charts, dashboards, and analytical insights using natural language processing.
        </p>
      </section>

      <section id="informational-purposes">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">2. Informational Purposes Only (No Financial Advice)</h2>
        <p className="mb-3 font-semibold text-foreground">IMPORTANT DISCLAIMER: Dreamify is an analytical tool, not a certified financial advisor, broker, or accounting firm.</p>
        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
          <li>Any charts, projections, risk assessments, or insights generated by our AI are for informational and educational purposes only.</li>
          <li>They do not constitute professional financial, investment, legal, or tax advice.</li>
          <li>You are solely responsible for any business, financial, or investment decisions you make based on the data processed by Dreamify. We assume no liability for any financial losses or damages incurred.</li>
        </ul>
      </section>

      <section id="user-accounts-security">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">3. User Accounts and Security</h2>
        <p className="text-muted-foreground leading-relaxed">
          To use certain features of the Service, you must register for an account (e.g., via Google OAuth). You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
        </p>
      </section>

      <section id="user-data-content">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">4. User Data and Content</h2>
        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
          <li><strong className="text-foreground font-medium">Ownership:</strong> You retain full ownership of all data, files, and information you upload or connect to the Service ("User Data"). Dreamify claims no ownership rights over your User Data.</li>
          <li><strong className="text-foreground font-medium">License to Process:</strong> By using the Service, you grant Dreamify a temporary, limited license to access, process, and transmit your User Data (including sending queries to third-party AI models like Google Gemini) solely for the purpose of generating the visualizations and insights you request.</li>
          <li><strong className="text-foreground font-medium">Responsibility:</strong> You are solely responsible for ensuring that you have the legal right and necessary permissions to upload or connect your User Data to Dreamify.</li>
        </ul>
      </section>

      <section id="acceptable-use">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">5. Acceptable Use Policy</h2>
        <p className="mb-3 text-muted-foreground">You agree not to use the Service to:</p>
        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
          <li>Upload any data that contains malicious code, viruses, or illegal content.</li>
          <li>Reverse engineer, decompile, or attempt to extract the source code or underlying AI prompts of the Service.</li>
          <li>Attempt to bypass any rate limits, security mechanisms, or API restrictions.</li>
          <li>Use the Service in any manner that could disable, overburden, or impair our servers.</li>
        </ul>
      </section>

      <section id="third-party-services">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">6. Third-Party Services and APIs</h2>
        <p className="text-muted-foreground leading-relaxed">
          Dreamify relies on third-party services, including Google APIs (e.g., Google Drive, Google Sheets, Google Analytics) and AI providers (e.g., Google Gemini). Your use of these integrations is also subject to the respective terms and conditions of those third parties. We are not responsible for the availability, accuracy, or reliability of any third-party services.
        </p>
      </section>

      <section id="disclaimer-warranties">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">7. Disclaimer of Warranties</h2>
        <div className="p-5 border border-border rounded-xl bg-card">
          <p className="text-sm text-muted-foreground uppercase tracking-wider leading-relaxed font-medium">
            THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. DREAMIFY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE AI-GENERATED INSIGHTS WILL BE ERROR-FREE, ACCURATE, OR UNINTERRUPTED.
          </p>
        </div>
      </section>

      <section id="limitation-liability">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">8. Limitation of Liability</h2>
        <div className="p-5 border border-border rounded-xl bg-card">
          <p className="text-sm text-muted-foreground uppercase tracking-wider leading-relaxed font-medium">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL DREAMIFY, ITS FOUNDERS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR USE OR INABILITY TO USE THE SERVICE; OR (B) ANY ERRORS OR INACCURACIES IN THE AI-GENERATED OUTPUT.
          </p>
        </div>
      </section>

      <section id="modifications-terms">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">9. Modifications to the Terms</h2>
        <p className="text-muted-foreground leading-relaxed">
          We reserve the right to modify these Terms at any time. If we make material changes, we will notify you by updating the "Effective Date" at the top of this document or by sending an email notification. Your continued use of the Service after the revised Terms become effective constitutes your acceptance of the changes.
        </p>
      </section>

      <section id="contact-us">
        <h2 className="text-2xl font-semibold mb-4 text-foreground">10. Contact Us</h2>
        <p className="text-muted-foreground mb-4">If you have any questions or concerns regarding these Terms, please contact us at:</p>
        <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
          <li><strong className="text-foreground font-medium">Email:</strong> <a href="mailto:dreamify.dev@gmail.com" className="text-primary hover:underline font-semibold">dreamify.dev@gmail.com</a></li>
        </ul>
      </section>
    </DocsLayout>
  );
};

export default Terms;
